name: beets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - beautifulsoup4 # for lyrics
  - oauthlib # for discogs_client
  - confuse # for beets
  - flask # for web
  - flask-cors # for web
  - imagemagick # for embedart
  - jellyfish # for beets
  - langdetect # for lyrics
  - mediafile # for beets
  - munkres # for beets
  - musicbrainzngs # for beets, beets-artistcountry
  - mutagen # for whatlastgenre
  - rauth # for whatlastgenre
  - requests # for fetchart, lyrics, whatlastgenre
  - requests-cache # for whatlastgenre
  - unidecode # for beets
  - pip
  - pip:
    - beets
    - beets-artistcountry
    - beets-ibroadcast
    - discogs_client # for discogs
    - git+https://github.com/igordertigor/beets-usertag.git
    - -e . # ctrpaths
